### ISSUE TITLE
Spotify broken after last spotilocal update

### ISSUE THREAD

**Issue by JeremyKruman** [mkloubert/vs-media-player#1]
Every time I try to connect to Spotify, the extension cannot see that Spotify is open. This started recently, right after the spotilocal package got updated to 0.2.0.

I'd guess that forcing the extension to use 0.1.0 in package.json would probably do the trick, but I'm no expert.

**Comment by mkloubert** [comment]
@JeremyKruman 

**I have released v1.6.0** and setup [package.json](https://github.com/mkloubert/vs-media-player/blob/master/package.json), which will only use [spotilocal](https://www.npmjs.com/package/spotilocal) module (`0.1.0`).

**Comment by JeremyKruman** [comment]
Thanks...strangely, I'm still seeing the same error:

It looks like spotify isn't open. We failed to find spotiflocal url with ports in range 4370-4380.

Spotify is definitely open, and it worked up until a few days ago, so I'm not sure what the issue is.

**Comment by JeremyKruman** [comment]
Upon doing some more research, it looks like a Spotify update broke all versions of spotilocal < 0.2.0. Is there any chance that this extension will be made compatible with the updated module in the future?

**Comment by mkloubert** [comment]
@JeremyKruman 

Thank you very much!

I have checked both version and the update to version 0.2.0 works now.

I will release a new version of the extension with the latest version of [spotilocal](https://www.npmjs.com/package/spotilocal) this evening (in about 8 hours).

**Comment by JeremyKruman** [comment]
Great! I'm looking forward to it 😄 thank you for all your work on this amazing extension!
